CREATE GLOBAL TEMPORARY TABLE "XXYSS_ADMIN"."PM_SYSSTAT_TMP" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"NAME" VARCHAR2(64) NOT NULL ENABLE, 
	"CLASS" NUMBER NOT NULL ENABLE, 
	"VALUE" NUMBER NOT NULL ENABLE, 
	"STAT_ID" NUMBER
   ) ON COMMIT PRESERVE ROWS;

