CREATE TABLE "PM_SYSSTAT" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(64) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CLASS" NUMBER NOT NULL ENABLE, 
	"VALUE" NUMBER NOT NULL ENABLE, 
	"STAT_ID" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

