CREATE TABLE "XXYSS_ADMIN"."PM_SYSTEM_EVENT" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"EVENT" VARCHAR2(64) NOT NULL ENABLE, 
	"TOTAL_WAITS" NUMBER(*,0) NOT NULL ENABLE, 
	"TOTAL_TIMEOUTS" NUMBER(*,0) NOT NULL ENABLE, 
	"TIME_WAITED" NUMBER NOT NULL ENABLE, 
	"AVERAGE_WAIT" NUMBER NOT NULL ENABLE, 
	"TIME_WAITED_MICRO" NUMBER, 
	"EVENT_ID" NUMBER, 
	"WAIT_CLASS_ID" NUMBER, 
	"WAIT_CLASS#" NUMBER, 
	"WAIT_CLASS" VARCHAR2(64)
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "YSSDATA";

