CREATE INDEX "PM_SES_SQL_FK1_FRGN" ON "PM_SESSION" ("DB", "SQL_HASH_VALUE", "SQL_ADDRESS") 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

CREATE UNIQUE INDEX "PM_SES_PK" ON "PM_SESSION" ("DB", "RUN_ID", "SID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

