CREATE INDEX "PM_SQL_SID_FK1_FRGN" ON "PM_SQL" ("SQL_ID") 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

CREATE UNIQUE INDEX "PM_SQL_PK" ON "PM_SQL" ("DB", "HASH_VALUE", "ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS";

