CREATE INDEX "XXYSS_ADMIN"."PM_SQL_SID_FK1_FRGN" ON "XXYSS_ADMIN"."PM_SQL" ("SQL_ID") 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_SQL_PK" ON "XXYSS_ADMIN"."PM_SQL" ("DB", "HASH_VALUE", "ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

