CREATE INDEX "XXYSS_ADMIN"."PM_RUN_1" ON "XXYSS_ADMIN"."PM_RUN" ("DB", "TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_RUN_PK" ON "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

