/*
    The Performance Monitor monitors your Oracle databases.
    Copyright (C) 2002  G.J. Paulissen, Transfer Solutions b.v., Leerdam, Netherlands

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*/
REM $Header$
REM
REM  This ORACLE7 command file was generated by Oracle Server Generator
REM  Version 5.5.8.0.0 on 01-DEC-97
REM
REM For application GSK version 1 database GSK
REM
SET SCAN OFF

SPOOL gskdb.lst
 
REM TABLE CREATION 
@@gskdb.tab
 
 
REM TABLE DATA INSERTION (added manually)
@@gskdb.dat
rem @@gsk_refc.dat
 
 
REM CONSTRAINT CREATION 
@@gskdb.con
 
 
REM PACKAGE CREATION 
@@gskdb.pck
 

REM
REM  End of command file
REM
SPOOL OFF

SET SCAN ON


