CREATE GLOBAL TEMPORARY TABLE "PM_SYSTEM_EVENT_TMP" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"EVENT" VARCHAR2(64) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"TOTAL_WAITS" NUMBER, 
	"TOTAL_TIMEOUTS" NUMBER, 
	"TIME_WAITED" NUMBER, 
	"AVERAGE_WAIT" NUMBER, 
	"TIME_WAITED_MICRO" NUMBER, 
	"EVENT_ID" NUMBER, 
	"WAIT_CLASS_ID" NUMBER, 
	"WAIT_CLASS#" NUMBER, 
	"WAIT_CLASS" VARCHAR2(64) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT PRESERVE ROWS;

