CREATE TABLE "PM_SESSION" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PROGRAM" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"SQL_HASH_VALUE" NUMBER, 
	"SQL_ADDRESS" VARCHAR2(32) COLLATE "USING_NLS_COMP", 
	"SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	"PREV_SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	"LOGON_TIME" DATE NOT NULL ENABLE, 
	"LAST_CALL_ET" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

