CREATE GLOBAL TEMPORARY TABLE "PM_SQLAREA_TMP" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FIRST_LOAD_TIME" DATE NOT NULL ENABLE, 
	"HASH_VALUE" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(32) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARSING_USER_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARSING_SCHEMA_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"EXECUTIONS" NUMBER, 
	"BUFFER_GETS" NUMBER, 
	"DISK_READS" NUMBER, 
	"PARSE_CALLS" NUMBER, 
	"SORTS" NUMBER, 
	"KEPT_VERSIONS" NUMBER, 
	"LOADS" NUMBER, 
	"ROWS_PROCESSED" NUMBER, 
	"INVALIDATIONS" NUMBER, 
	"MODULE" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"ACTION" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"SQL_TEXT" CLOB COLLATE "USING_NLS_COMP", 
	"COMMAND_TYPE" NUMBER, 
	"SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DIRECT_WRITES" NUMBER, 
	"APPLICATION_WAIT_TIME" NUMBER, 
	"CONCURRENCY_WAIT_TIME" NUMBER, 
	"CLUSTER_WAIT_TIME" NUMBER, 
	"USER_IO_WAIT_TIME" NUMBER, 
	"PLSQL_EXEC_TIME" NUMBER, 
	"JAVA_EXEC_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"SQL_PROFILE" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"PROGRAM_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"PROGRAM_LINE#" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT PRESERVE ROWS 
 LOB ("SQL_TEXT") STORE AS BASICFILE (
  ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE );

