CREATE GLOBAL TEMPORARY TABLE "PM_SESSION_TMP" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"SID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"PROGRAM" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"SQL_HASH_VALUE" NUMBER, 
	"SQL_ADDRESS" VARCHAR2(32) COLLATE "USING_NLS_COMP", 
	"SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	"PREV_SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP", 
	"LOGON_TIME" DATE NOT NULL ENABLE, 
	"LAST_CALL_ET" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP" ON COMMIT PRESERVE ROWS;

