prompt @01.SEQUENCE.PM_RUN_SEQ.sql
@01.SEQUENCE.PM_RUN_SEQ.sql
prompt @01.SEQUENCE.PM_SQL_SEQ.sql
@01.SEQUENCE.PM_SQL_SEQ.sql
prompt @06.TABLE.PM_RUN.sql
@06.TABLE.PM_RUN.sql
prompt @06.TABLE.PM_SESSION.sql
@06.TABLE.PM_SESSION.sql
prompt @06.TABLE.PM_SESSION_TMP.sql
@06.TABLE.PM_SESSION_TMP.sql
prompt @06.TABLE.PM_SQL.sql
@06.TABLE.PM_SQL.sql
prompt @06.TABLE.PM_SQLAREA.sql
@06.TABLE.PM_SQLAREA.sql
prompt @06.TABLE.PM_SQLAREA_TMP.sql
@06.TABLE.PM_SQLAREA_TMP.sql
prompt @06.TABLE.PM_SQL_CURRENT.sql
@06.TABLE.PM_SQL_CURRENT.sql
prompt @06.TABLE.PM_SQL_ID.sql
@06.TABLE.PM_SQL_ID.sql
prompt @06.TABLE.PM_SYSSTAT.sql
@06.TABLE.PM_SYSSTAT.sql
prompt @06.TABLE.PM_SYSSTAT_TMP.sql
@06.TABLE.PM_SYSSTAT_TMP.sql
prompt @06.TABLE.PM_SYSTEM_EVENT.sql
@06.TABLE.PM_SYSTEM_EVENT.sql
prompt @06.TABLE.PM_SYSTEM_EVENT_TMP.sql
@06.TABLE.PM_SYSTEM_EVENT_TMP.sql
prompt @R__09.PACKAGE_SPEC.PM.sql
@R__09.PACKAGE_SPEC.PM.sql
prompt @R__09.PACKAGE_SPEC.PM_DPI.sql
@R__09.PACKAGE_SPEC.PM_DPI.sql
prompt @R__09.PACKAGE_SPEC.PM_MPI.sql
@R__09.PACKAGE_SPEC.PM_MPI.sql
prompt @R__10.VIEW.PM_VW_SQLAREA.sql
@R__10.VIEW.PM_VW_SQLAREA.sql
prompt @R__14.PACKAGE_BODY.PM.sql
@R__14.PACKAGE_BODY.PM.sql
prompt @16.INDEX.PM_SQLAREA.sql
@16.INDEX.PM_SQLAREA.sql
prompt @16.INDEX.PM_SQLAREA_TMP.sql
@16.INDEX.PM_SQLAREA_TMP.sql
prompt @16.INDEX.PM_SQL_CURRENT.sql
@16.INDEX.PM_SQL_CURRENT.sql
prompt @16.INDEX.PM_RUN.sql
@16.INDEX.PM_RUN.sql
prompt @16.INDEX.PM_SESSION.sql
@16.INDEX.PM_SESSION.sql
prompt @16.INDEX.PM_SYSTEM_EVENT_TMP.sql
@16.INDEX.PM_SYSTEM_EVENT_TMP.sql
prompt @16.INDEX.PM_SYSTEM_EVENT.sql
@16.INDEX.PM_SYSTEM_EVENT.sql
prompt @16.INDEX.PM_SQL_ID.sql
@16.INDEX.PM_SQL_ID.sql
prompt @16.INDEX.PM_SQL.sql
@16.INDEX.PM_SQL.sql
prompt @16.INDEX.PM_SESSION_TMP.sql
@16.INDEX.PM_SESSION_TMP.sql
prompt @16.INDEX.PM_SYSSTAT.sql
@16.INDEX.PM_SYSSTAT.sql
prompt @16.INDEX.PM_SYSSTAT_TMP.sql
@16.INDEX.PM_SYSSTAT_TMP.sql
prompt @19.CONSTRAINT.PM_SQLAREA.sql
@19.CONSTRAINT.PM_SQLAREA.sql
prompt @19.CONSTRAINT.PM_SQL_CURRENT.sql
@19.CONSTRAINT.PM_SQL_CURRENT.sql
prompt @19.CONSTRAINT.PM_RUN.sql
@19.CONSTRAINT.PM_RUN.sql
prompt @19.CONSTRAINT.PM_SESSION.sql
@19.CONSTRAINT.PM_SESSION.sql
prompt @19.CONSTRAINT.PM_SYSTEM_EVENT_TMP.sql
@19.CONSTRAINT.PM_SYSTEM_EVENT_TMP.sql
prompt @19.CONSTRAINT.PM_SYSTEM_EVENT.sql
@19.CONSTRAINT.PM_SYSTEM_EVENT.sql
prompt @19.CONSTRAINT.PM_SQL_ID.sql
@19.CONSTRAINT.PM_SQL_ID.sql
prompt @19.CONSTRAINT.PM_SQL.sql
@19.CONSTRAINT.PM_SQL.sql
prompt @19.CONSTRAINT.PM_SESSION_TMP.sql
@19.CONSTRAINT.PM_SESSION_TMP.sql
prompt @19.CONSTRAINT.PM_SYSSTAT.sql
@19.CONSTRAINT.PM_SYSSTAT.sql
prompt @19.CONSTRAINT.PM_SYSSTAT_TMP.sql
@19.CONSTRAINT.PM_SYSSTAT_TMP.sql
prompt @20.REF_CONSTRAINT.PM_SQLAREA.sql
@20.REF_CONSTRAINT.PM_SQLAREA.sql
prompt @20.REF_CONSTRAINT.PM_SESSION.sql
@20.REF_CONSTRAINT.PM_SESSION.sql
prompt @20.REF_CONSTRAINT.PM_SYSTEM_EVENT.sql
@20.REF_CONSTRAINT.PM_SYSTEM_EVENT.sql
prompt @20.REF_CONSTRAINT.PM_SQL.sql
@20.REF_CONSTRAINT.PM_SQL.sql
prompt @20.REF_CONSTRAINT.PM_SYSSTAT.sql
@20.REF_CONSTRAINT.PM_SYSSTAT.sql
