/* SQL statement 32 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SYS_PK;XXYSS_ADMIN;TABLE;PM_SYSSTAT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSSTAT" ADD CONSTRAINT "PM_SYS_PK" PRIMARY KEY ("DB", "RUN_ID", "NAME") ENABLE;

