/* SQL statement 39 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SEV_PK;XXYSS_ADMIN;TABLE;PM_SYSTEM_EVENT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSTEM_EVENT" ADD CONSTRAINT "PM_SEV_PK" PRIMARY KEY ("DB", "RUN_ID", "EVENT") ENABLE;

