/* SQL statement 46 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_ARE_RUN_FK1;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQLAREA" ADD CONSTRAINT "PM_ARE_RUN_FK1" FOREIGN KEY ("DB", "RUN_ID")
	  REFERENCES "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") ENABLE;

