/* SQL statement 19 (CREATE;XXYSS_ADMIN;INDEX;PM_SQL_PK;XXYSS_ADMIN;TABLE;PM_SQL;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_SQL_PK" ON "XXYSS_ADMIN"."PM_SQL" ("DB", "HASH_VALUE", "ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

