/* SQL statement 28 (CREATE;XXYSS_ADMIN;INDEX;PM_CFG_PK;XXYSS_ADMIN;TABLE;PM_CONFIG;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_CFG_PK" ON "XXYSS_ADMIN"."PM_CONFIG" ("DB", "CFG_NR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

