/* SQL statement 40 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SET_PK;XXYSS_ADMIN;TABLE;PM_SYSTEM_EVENT_TMP;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSTEM_EVENT_TMP" ADD CONSTRAINT "PM_SET_PK" PRIMARY KEY ("DB", "RUN_ID", "EVENT") ENABLE;

