/* SQL statement 61 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SYS_CK2;XXYSS_ADMIN;TABLE;PM_SYSSTAT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSSTAT" ADD CONSTRAINT "PM_SYS_CK2" CHECK (
      value >= 0
      ) ENABLE;

