/* SQL statement 43 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_SYS_RUN_FK1;XXYSS_ADMIN;TABLE;PM_SYSSTAT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSSTAT" ADD CONSTRAINT "PM_SYS_RUN_FK1" FOREIGN KEY ("DB", "RUN_ID")
	  REFERENCES "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") ENABLE;

