/* SQL statement 20 (CREATE;XXYSS_ADMIN;INDEX;PM_SID_PK;XXYSS_ADMIN;TABLE;PM_SQL_ID;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_SID_PK" ON "XXYSS_ADMIN"."PM_SQL_ID" ("SQL_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

