/* SQL statement 50 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_ARE_CK1;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQLAREA" ADD CONSTRAINT "PM_ARE_CK1" CHECK (
      db = upper(db) and
      run_id >= 1
      ) ENABLE;

