/* SQL statement 48 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_CFG_PK;XXYSS_ADMIN;TABLE;PM_CONFIG;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_CONFIG" ADD CONSTRAINT "PM_CFG_PK" PRIMARY KEY ("DB", "CFG_NR") ENABLE;

