/* SQL statement 27 (CREATE;XXYSS_ADMIN;INDEX;PM_CUR_PK;XXYSS_ADMIN;TABLE;PM_SQL_CURRENT;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_CUR_PK" ON "XXYSS_ADMIN"."PM_SQL_CURRENT" ("DB", "HASH_VALUE", "ADDRESS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

