/* SQL statement 49 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_ARE_PK;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQLAREA" ADD CONSTRAINT "PM_ARE_PK" PRIMARY KEY ("DB", "HASH_VALUE", "ADDRESS", "FIRST_LOAD_TIME", "PARSING_USER_NAME", "PARSING_SCHEMA_NAME", "RUN_ID") ENABLE;

