/* SQL statement 35 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_SES_SQL_FK1;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SESSION" ADD CONSTRAINT "PM_SES_SQL_FK1" FOREIGN KEY ("DB", "SQL_HASH_VALUE", "SQL_ADDRESS")
	  REFERENCES "XXYSS_ADMIN"."PM_SQL" ("DB", "HASH_VALUE", "ADDRESS") ENABLE;

