/* SQL statement 10 (CREATE;XXYSS_ADMIN;TABLE;PM_SESSION_TMP;;;;;;;;2) */
begin
  execute immediate '
CREATE GLOBAL TEMPORARY TABLE "XXYSS_ADMIN"."PM_SESSION_TMP" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"RUN_ID" NUMBER NOT NULL ENABLE, 
	"SID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30), 
	"PROGRAM" VARCHAR2(64), 
	"SQL_HASH_VALUE" NUMBER, 
	"SQL_ADDRESS" VARCHAR2(32), 
	"SQL_ID" VARCHAR2(13), 
	"PREV_SQL_ID" VARCHAR2(13), 
	"LOGON_TIME" DATE NOT NULL ENABLE, 
	"LAST_CALL_ET" NUMBER
   ) ON COMMIT PRESERVE ROWS';
end;
/

