/* SQL statement 11 (CREATE;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;;;;2) */
CREATE TABLE "XXYSS_ADMIN"."PM_SESSION" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"SID" NUMBER NOT NULL ENABLE, 
	"USERNAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PROGRAM" VARCHAR2(64), 
	"SQL_HASH_VALUE" NUMBER, 
	"SQL_ADDRESS" VARCHAR2(32), 
	"SQL_ID" VARCHAR2(13), 
	"PREV_SQL_ID" VARCHAR2(13), 
	"LOGON_TIME" DATE NOT NULL ENABLE, 
	"LAST_CALL_ET" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "YSSDATA";

