/* SQL statement 34 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SQL_PK;XXYSS_ADMIN;TABLE;PM_SQL;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQL" ADD CONSTRAINT "PM_SQL_PK" PRIMARY KEY ("DB", "HASH_VALUE", "ADDRESS") ENABLE;

