/* SQL statement 47 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_CUR_PK;XXYSS_ADMIN;TABLE;PM_SQL_CURRENT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQL_CURRENT" ADD CONSTRAINT "PM_CUR_PK" PRIMARY KEY ("DB", "HASH_VALUE", "ADDRESS") ENABLE;

