REM Generated by perl cmd2sql.pl (1.12)

REMARK *************************************************************************
REMARK Start of section 1
REMARK Please do NOT edit this section.
REMARK *************************************************************************

WHENEVER OSERROR CONTINUE
SET DEFINE '&'
SET FEEDBACK OFF VERIFY OFF TERMOUT OFF
COLUMN sessionid NEW_VALUE sessionid
SELECT LTRIM(USERENV('SESSIONID')) sessionid
FROM DUAL
/
DEFINE env_sql = 'env.&&sessionid..sql'
DEFINE connect_sql = 'connect.&&sessionid..sql'
DEFINE restore_sql = 'restore.&&sessionid..sql'
DEFINE restore1_sql = 'restore1.&&sessionid..sql'
DEFINE restore2_sql = 'restore2.&&sessionid..sql'
DEFINE host_bat = 'host.&&sessionid..bat'
SET FEEDBACK ON VERIFY ON TERMOUT ON
SET TERMOUT OFF SQLPROMPT '--'
UNDEFINE _O_VERSION
SPOOL &&restore_sql
PROMPT @&&restore1_sql
PROMPT @&&restore2_sql
SPOOL &&restore1_sql
SET DEFINE OFF
DEFINE
SET DEFINE '&'
PROMPT WHENEVER SQLERROR EXIT FAILURE
PROMPT WHENEVER OSERROR EXIT FAILURE
SPOOL OFF
SET TERMOUT ON SQLPROMPT 'SQL> '
STORE SET &&restore2_sql CREATE
PROMPT Starting session &&sessionid

SET TERMOUT OFF SQLPROMPT '' VERIFY OFF ECHO OFF
SPOOL &&connect_sql
PROMPT SET DEFINE '~' VERIFY OFF FEEDBACK OFF PAGESIZE 0 TERMOUT OFF ECHO OFF
PROMPT WHENEVER SQLERROR EXIT FAILURE
PROMPT PROMPT Connecting to ~~1
PROMPT CONNECT ~~1
PROMPT SET DEFINE '&'
PROMPT UNDEFINE 1
PROMPT START &&restore_sql
SPOOL OFF
SET DEFINE '&'
START &&restore_sql

SET TERMOUT OFF SQLPROMPT '' VERIFY OFF ECHO OFF
SPOOL &&env_sql
PROMPT SET DEFINE '~'
PROMPT SET FEEDBACK OFF VERIFY OFF TERMOUT OFF ECHO OFF
PROMPT COLUMN delete_cmd FORMAT a20 NEW_VALUE delete_cmd
PROMPT COLUMN copy_cmd FORMAT a20 NEW_VALUE copy_cmd
PROMPT COLUMN batch_cmd FORMAT a20 NEW_VALUE batch_cmd
PROMPT COLUMN begin_cmd FORMAT a20 NEW_VALUE begin_cmd
PROMPT COLUMN end_cmd FORMAT a40 NEW_VALUE end_cmd
PROMPT COLUMN create_file_cmd FORMAT a20 NEW_VALUE create_file_cmd
PROMPT COLUMN set_file_readonly_cmd FORMAT a30 NEW_VALUE set_file_readonly_cmd
PROMPT COLUMN set_file_writable_cmd FORMAT a30 NEW_VALUE set_file_writable_cmd
PROMPT COLUMN on_error_exit_cmd FORMAT a30 NEW_VALUE on_error_exit_cmd
PROMPT COLUMN ignore_stdout FORMAT a30 NEW_VALUE ignore_stdout
PROMPT DEFINE os = 'Windows'
PROMPT REM accept os prompt 'Operating System (Windows|Unix) ? [~~os] ' default ~~os
PROMPT SELECT 'del' delete_cmd
PROMPT ,      'copy' copy_cmd
PROMPT ,      'call' batch_cmd
PROMPT ,      '@echo on' begin_cmd
PROMPT ,      '@exit' || chr(10) || ':error' || chr(10) || '@echo ERROR: last command failed.' || chr(10) || '@pause' end_cmd
PROMPT ,      '@echo. >' create_file_cmd
PROMPT ,      '@attrib +R' set_file_readonly_cmd
PROMPT ,      '@attrib -R' set_file_writable_cmd
PROMPT ,      '@if errorlevel 1 goto error' on_error_exit_cmd
PROMPT ,      '>nul' ignore_stdout
PROMPT FROM DUAL
PROMPT WHERE UPPER('~~os') LIKE 'WIN%'
PROMPT UNION ALL
PROMPT SELECT 'rm' delete_cmd
PROMPT ,      'cp' copy_cmd
PROMPT ,      'sh' batch_cmd
PROMPT ,      'ps1=$PS1; PS1=">"' begin_cmd
PROMPT ,      'PS1=$ps1' end_cmd
PROMPT ,      'touch' create_file_cmd
PROMPT ,      'chmod -w' set_file_readonly_cmd
PROMPT ,      'chmod +w' set_file_writable_cmd
PROMPT ,      'test $? -eq 0 || exit' on_error_exit_cmd
PROMPT ,      '1>/dev/null' ignore_stdout
PROMPT FROM DUAL
PROMPT WHERE UPPER('~~os') LIKE '%X'
PROMPT /
PROMPT UNDEFINE os
PROMPT SET DEFINE '&'
PROMPT COLUMN delete_cmd CLEAR
PROMPT COLUMN copy_cmd CLEAR
PROMPT COLUMN batch_cmd CLEAR
PROMPT COLUMN begin_cmd CLEAR
PROMPT COLUMN end_cmd CLEAR
PROMPT COLUMN create_file_cmd CLEAR
PROMPT COLUMN set_file_readonly_cmd CLEAR
PROMPT COLUMN set_file_writable_cmd CLEAR
PROMPT COLUMN on_error_exit_cmd CLEAR
PROMPT COLUMN ignore_stdout CLEAR
PROMPT START &&restore_sql
SPOOL OFF
SET DEFINE '&'
START &&restore_sql

WHENEVER OSERROR EXIT FAILURE
START &&env_sql
REMARK *************************************************************************
REMARK End of section 1
REMARK *************************************************************************

REMARK *************************************************************************
REMARK Start of section 2
REMARK This section may be edited.
REMARK *************************************************************************

COMMIT
/

DEFINE log_file = 'output00001.&&sessionid..log'
PROMPT Log file: &&log_file
SPOOL &&log_file
START &&restore_sql
SET VERIFY OFF DEFINE OFF
PROMPT Command: START &&pm_HOME\common/src/sql/set_common_sql_dir.sql "&&pm_HOME\common/src/sql/"
SET VERIFY ON DEFINE ON
PROMPT &&pm_HOME
START &&pm_HOME\common/src/sql/set_common_sql_dir.sql "&&pm_HOME\common/src/sql/"
SET DEFINE '&'
COMMIT
/

DEFINE log_file = 'output00002.&&sessionid..log'
PROMPT Log file: &&log_file
SPOOL &&log_file
START &&restore_sql
SET VERIFY OFF DEFINE OFF
PROMPT Command: START &&pm_HOME\common/src/sql/check_sql_env.sql RELEASE pm "<=" &&pm_VERSION ""
SET VERIFY ON DEFINE ON
PROMPT &&pm_VERSION
START &&pm_HOME\common/src/sql/check_sql_env.sql RELEASE pm "<=" &&pm_VERSION ""
SET DEFINE '&'
COMMIT
/

DEFINE log_file = 'output00003.&&sessionid..log'
PROMPT Log file: &&log_file
SPOOL &&log_file
START &&restore_sql
SET VERIFY OFF DEFINE OFF
PROMPT Command: START &&pm_HOME\common/src/sql/check_sql_env.sql CONTINUE "EXIT FAILURE"
SET VERIFY ON DEFINE ON
START &&pm_HOME\common/src/sql/check_sql_env.sql CONTINUE "EXIT FAILURE"
SET DEFINE '&'
COMMIT
/

DEFINE log_file = 'output00004.&&sessionid..log'
PROMPT &&FRMGEN
PROMPT &&userid
PROMPT &&FRM_BIN
PROMPT &&RPT_BIN
PROMPT &&RPTGEN
SET TERMOUT OFF SQLPROMPT '' VERIFY OFF ECHO OFF
SPOOL &&host_bat
PROMPT &&begin_cmd
PROMPT &&create_file_cmd &&log_file
PROMPT &&set_file_readonly_cmd &&log_file
PROMPT if exist "&&pm_HOME\report\" copy "&&pm_HOME\report\" "."
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing menus: START ***
PROMPT &&on_error_exit_cmd
PROMPT echo @echo off> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set NLS_LANG=AMERICAN_AMERICA.WE8ISO8859P1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set PROGRAM=%%1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo shift>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set USERID=%%1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo shift>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set ERROR_FILE=%%1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo shift>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set INPUT_FILE=%%2>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set OUTPUT_FILE=%%4>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set PARAMETERS=USERID=%%USERID%%>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo rem FLAGS in VAR=VALUE pairs.>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo :loop>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%1" == "" goto run>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set PARAMETERS=%%PARAMETERS%% %%1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%2" == "" goto run>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo set PARAMETERS=%%PARAMETERS%%=%%2>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo shift>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo shift>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo goto loop>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo :run>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%PROGRAM%%" == """" goto usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%USERID%%" == """" goto usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%ERROR_FILE%%" == "" goto usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%INPUT_FILE%%" == "" goto usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo if "%%OUTPUT_FILE%%" == "" goto usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo echo on>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @if exist "%%OUTPUT_FILE%%" del "%%OUTPUT_FILE%%">> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo %%PROGRAM%% %%PARAMETERS%%>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo dir /b %%OUTPUT_FILE%%>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @if errorlevel 1 goto error>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @goto end>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo :error>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @echo ERROR: Could not create '%%OUTPUT_FILE%%' from '%%INPUT_FILE%%'.>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @echo Wrong connection (%%USERID%%) or see file '%%ERROR_FILE%%' for details.>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @pause>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @exit 1 1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo :usage>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @echo USAGE: run_ora_prog PROGRAM USERID ERROR_FILE 'SRC'=.. 'DST'=.. [ VAR1=VAL1 ... VARn=VALn ]>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @pause>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo @exit 1 1>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT echo :end>> run_ora_prog.bat
PROMPT &&on_error_exit_cmd
PROMPT if exist "pm_mnu_tmp.mmb" del "pm_mnu_tmp.mmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm_mnu.mmb" "pm_mnu_tmp.mmb"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" pm_mnu_tmp.err MODULE="pm_mnu_tmp.mmb" OUTPUT_FILE="pm_mnu.mmx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=MENU COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "pm_mnu_tmp.mmb"
PROMPT &&on_error_exit_cmd
PROMPT if not exist "&&FRM_BIN" mkdir "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "pm_mnu.mmx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing menus: OK ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing forms_libs: START ***
PROMPT &&on_error_exit_cmd
PROMPT if exist "gskgen_tmp.pll" del "gskgen_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\gskgen.pll" "gskgen_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" gskgen_tmp.err MODULE="gskgen_tmp.pll" OUTPUT_FILE="gskgen.plx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=LIBRARY STRIP_SOURCE=YES COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "gskgen_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT copy "gskgen.plx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT if exist "OFG4HPL_tmp.pll" del "OFG4HPL_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\OFG4HPL.pll" "OFG4HPL_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" OFG4HPL_tmp.err MODULE="OFG4HPL_tmp.pll" OUTPUT_FILE="OFG4HPL.plx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=LIBRARY STRIP_SOURCE=YES COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "OFG4HPL_tmp.pll"
PROMPT &&on_error_exit_cmd
PROMPT copy "OFG4HPL.plx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing forms_libs: OK ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing icons: START ***
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\abort.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\abort.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afclrall.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afclrall.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afclrrw.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afclrrw.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afdelrw.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afdelrw.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afedit.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afedit.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affind.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affind.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afflddwn.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afflddwn.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldlft.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldlft.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldrt.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldrt.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldup.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\affldup.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afhelp.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afhelp.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afinsrw.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afinsrw.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\aflist.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\aflist.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afprint.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afprint.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afquery.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afquery.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afsave.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\afsave.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\entqry.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\entqry.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\keys.gif" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\keys.ico" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT if not exist "&&RPT_BIN" mkdir "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm_logo.gif" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing icons: OK ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing forms: START ***
PROMPT &&on_error_exit_cmd
PROMPT if exist "pm_about_tmp.fmb" del "pm_about_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm_about.fmb" "pm_about_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" pm_about_tmp.err MODULE="pm_about_tmp.fmb" OUTPUT_FILE="pm_about.fmx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=FORM COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "pm_about_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "pm_about.fmx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT if exist "pm_params_tmp.fmb" del "pm_params_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm_params.fmb" "pm_params_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" pm_params_tmp.err MODULE="pm_params_tmp.fmb" OUTPUT_FILE="pm_params.fmx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=FORM COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "pm_params_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "pm_params.fmx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT if exist "pm_start_tmp.fmb" del "pm_start_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm_start.fmb" "pm_start_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&FRMGEN" "&&userid" pm_start_tmp.err MODULE="pm_start_tmp.fmb" OUTPUT_FILE="pm_start.fmx" BATCH=YES WINDOW_STATE=minimize MODULE_TYPE=FORM COMPILE_ALL=YES
PROMPT &&on_error_exit_cmd
PROMPT del "pm_start_tmp.fmb"
PROMPT &&on_error_exit_cmd
PROMPT copy "pm_start.fmx" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing forms: OK ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing reports_libs: START ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing reports_libs: OK ***
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing reports: START ***
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm001.rdf" DEST="pm001.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm001.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm0041.rdf" DEST="pm0041.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm0041.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm0042.rdf" DEST="pm0042.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm0042.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm0043.rdf" DEST="pm0043.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm0043.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm005.rdf" DEST="pm005.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm005.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm007.rdf" DEST="pm007.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm007.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm008.rdf" DEST="pm008.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm008.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm009.rdf" DEST="pm009.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm009.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm010.rdf" DEST="pm010.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm010.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm011.rdf" DEST="pm011.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm011.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm012.rdf" DEST="pm012.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm012.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT call "run_ora_prog.bat" "&&RPTGEN" "&&userid" reports.log SOURCE="&&pm_HOME\report\pm013.rdf" DEST="pm013.rep" BATCH=YES STYPE=RDFFILE DTYPE=REPFILE OVERWRITE=YES
PROMPT &&on_error_exit_cmd
PROMPT copy "pm013.rep" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT echo *** Installing reports: OK ***
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm012.ogd" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm001q2.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm0041q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm0042q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm0043q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm005q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm007q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm008q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm009q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm010q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm011q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm012q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\report\pm013q1.sql" "&&RPT_BIN"
PROMPT &&on_error_exit_cmd
PROMPT if not exist "&&pm_HOME\html" mkdir "&&pm_HOME\html"
PROMPT &&on_error_exit_cmd
PROMPT copy "&&pm_HOME\VERSION" "&&FRM_BIN"
PROMPT &&on_error_exit_cmd
PROMPT &&set_file_writable_cmd &&log_file
PROMPT &&end_cmd
SPOOL OFF
SET DEFINE '&'
START &&restore_sql
HOST &&batch_cmd &&host_bat
PROMPT Log file: &&log_file
SPOOL &&log_file

SPOOL OFF
REMARK *************************************************************************
REMARK End of section 2
REMARK *************************************************************************

REMARK *************************************************************************
REMARK Start of section 3
REMARK Please do NOT edit this section.
REMARK *************************************************************************

WHENEVER OSERROR CONTINUE
HOST &&copy_cmd output?????.&&sessionid..log output.&&sessionid..tmp &&ignore_stdout
HOST &&delete_cmd output?????.&&sessionid..log &&ignore_stdout
HOST &&copy_cmd output.&&sessionid..tmp output.&&sessionid..log &&ignore_stdout
HOST &&delete_cmd output.&&sessionid..tmp &&ignore_stdout
HOST &&delete_cmd &&connect_sql &&ignore_stdout
HOST &&delete_cmd &&restore_sql &&ignore_stdout
HOST &&delete_cmd &&restore1_sql &&ignore_stdout
HOST &&delete_cmd &&restore2_sql &&ignore_stdout
HOST &&delete_cmd &&env_sql &&ignore_stdout
HOST &&delete_cmd &&host_bat &&ignore_stdout
UNDEFINE batch_cmd
UNDEFINE begin_cmd
UNDEFINE connect_sql
UNDEFINE copy_cmd
UNDEFINE create_file_cmd
UNDEFINE delete_cmd
UNDEFINE end_cmd
UNDEFINE env_sql
UNDEFINE host_bat
UNDEFINE ignore_stdout
UNDEFINE log_file
UNDEFINE on_error_exit_cmd
UNDEFINE restore1_sql
UNDEFINE restore2_sql
UNDEFINE restore_sql
UNDEFINE sessionid
UNDEFINE set_file_readonly_cmd
UNDEFINE set_file_writable_cmd
REMARK *************************************************************************
REMARK End of section 3
REMARK *************************************************************************

SET TERMOUT ON SQLPROMPT 'SQL> '
PROMPT pm_build.sql READY. Enter EXIT to leave SQL*Plus... 
