/* SQL statement 33 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_STP_PK;XXYSS_ADMIN;TABLE;PM_SESSION_TMP;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SESSION_TMP" ADD CONSTRAINT "PM_STP_PK" PRIMARY KEY ("DB", "RUN_ID", "SID") ENABLE;

