/* SQL statement 18 (CREATE;XXYSS_ADMIN;INDEX;PM_SQL_SID_FK1_FRGN;XXYSS_ADMIN;TABLE;PM_SQL;;;;;2) */
CREATE INDEX "XXYSS_ADMIN"."PM_SQL_SID_FK1_FRGN" ON "XXYSS_ADMIN"."PM_SQL" ("SQL_ID") 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

