/* SQL statement 26 (CREATE;XXYSS_ADMIN;INDEX;PM_RUN_1;XXYSS_ADMIN;TABLE;PM_RUN;;;;;2) */
CREATE INDEX "XXYSS_ADMIN"."PM_RUN_1" ON "XXYSS_ADMIN"."PM_RUN" ("DB", "TIMESTAMP") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

