/* SQL statement 23 (CREATE;XXYSS_ADMIN;INDEX;PM_SES_SQL_FK1_FRGN;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;2) */
CREATE INDEX "XXYSS_ADMIN"."PM_SES_SQL_FK1_FRGN" ON "XXYSS_ADMIN"."PM_SESSION" ("DB", "SQL_HASH_VALUE", "SQL_ADDRESS") 
  PCTFREE 0 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

