/* SQL statement 45 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_SES_RUN_FK1;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SESSION" ADD CONSTRAINT "PM_SES_RUN_FK1" FOREIGN KEY ("DB", "RUN_ID")
	  REFERENCES "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") ENABLE;

