/* SQL statement 55 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SES_CK1;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SESSION" ADD CONSTRAINT "PM_SES_CK1" CHECK (
      db = upper(db) and
      run_id >= 1
      ) ENABLE;

