/* SQL statement 17 (CREATE;XXYSS_ADMIN;INDEX;PM_STP_PK;XXYSS_ADMIN;TABLE;PM_SESSION_TMP;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_STP_PK" ON "XXYSS_ADMIN"."PM_SESSION_TMP" ("DB", "RUN_ID", "SID");

