/* SQL statement 41 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SES_PK;XXYSS_ADMIN;TABLE;PM_SESSION;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SESSION" ADD CONSTRAINT "PM_SES_PK" PRIMARY KEY ("DB", "RUN_ID", "SID") ENABLE;

