/* SQL statement 22 (CREATE;XXYSS_ADMIN;INDEX;PM_SET_PK;XXYSS_ADMIN;TABLE;PM_SYSTEM_EVENT_TMP;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_SET_PK" ON "XXYSS_ADMIN"."PM_SYSTEM_EVENT_TMP" ("DB", "RUN_ID", "EVENT");

