/* SQL statement 30 (CREATE;XXYSS_ADMIN;INDEX;PM_ARE_PK;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_ARE_PK" ON "XXYSS_ADMIN"."PM_SQLAREA" ("DB", "HASH_VALUE", "ADDRESS", "FIRST_LOAD_TIME", "PARSING_USER_NAME", "PARSING_SCHEMA_NAME", "RUN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

