/* SQL statement 60 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SYS_CK1;XXYSS_ADMIN;TABLE;PM_SYSSTAT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSSTAT" ADD CONSTRAINT "PM_SYS_CK1" CHECK (
      db = upper(db) and
      run_id >= 1
      ) ENABLE;

