/* SQL statement 38 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_SQL_SID_FK1;XXYSS_ADMIN;TABLE;PM_SQL;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQL" ADD CONSTRAINT "PM_SQL_SID_FK1" FOREIGN KEY ("SQL_ID")
	  REFERENCES "XXYSS_ADMIN"."PM_SQL_ID" ("SQL_ID") ENABLE;

