/* SQL statement 25 (CREATE;XXYSS_ADMIN;INDEX;PM_RUN_PK;XXYSS_ADMIN;TABLE;PM_RUN;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_RUN_PK" ON "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "YSSDATA";

