/* SQL statement 44 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_SEV_RUN_FK1;XXYSS_ADMIN;TABLE;PM_SYSTEM_EVENT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSTEM_EVENT" ADD CONSTRAINT "PM_SEV_RUN_FK1" FOREIGN KEY ("DB", "RUN_ID")
	  REFERENCES "XXYSS_ADMIN"."PM_RUN" ("DB", "RUN_ID") ENABLE;

