/* SQL statement 36 (ALTER;XXYSS_ADMIN;REF_CONSTRAINT;PM_ARE_SQL_FK1;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQLAREA" ADD CONSTRAINT "PM_ARE_SQL_FK1" FOREIGN KEY ("DB", "HASH_VALUE", "ADDRESS")
	  REFERENCES "XXYSS_ADMIN"."PM_SQL" ("DB", "HASH_VALUE", "ADDRESS") ENABLE;

