/* SQL statement 29 (CREATE;XXYSS_ADMIN;INDEX;PM_ART_1;XXYSS_ADMIN;TABLE;PM_SQLAREA_TMP;;;;;2) */
CREATE INDEX "XXYSS_ADMIN"."PM_ART_1" ON "XXYSS_ADMIN"."PM_SQLAREA_TMP" ("DB", "FIRST_LOAD_TIME", "ADDRESS", "HASH_VALUE", "PARSING_USER_NAME", "PARSING_SCHEMA_NAME");

