/* SQL statement 15 (CREATE;XXYSS_ADMIN;INDEX;PM_SYT_PK;XXYSS_ADMIN;TABLE;PM_SYSSTAT_TMP;;;;;2) */
CREATE UNIQUE INDEX "XXYSS_ADMIN"."PM_SYT_PK" ON "XXYSS_ADMIN"."PM_SYSSTAT_TMP" ("DB", "RUN_ID", "NAME");

