/* SQL statement 59 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SQL_CK1;XXYSS_ADMIN;TABLE;PM_SQL;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SQL" ADD CONSTRAINT "PM_SQL_CK1" CHECK (
      db = upper(db)
      ) ENABLE;

