/* SQL statement 8 (CREATE;XXYSS_ADMIN;TABLE;PM_SQLAREA;;;;;;;;2) */
CREATE TABLE "XXYSS_ADMIN"."PM_SQLAREA" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"FIRST_LOAD_TIME" DATE NOT NULL ENABLE, 
	"HASH_VALUE" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(32) NOT NULL ENABLE, 
	"PARSING_USER_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"PARSING_SCHEMA_NAME" VARCHAR2(30) NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"EXECUTIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"BUFFER_GETS" NUMBER(*,0) NOT NULL ENABLE, 
	"DISK_READS" NUMBER(*,0) NOT NULL ENABLE, 
	"PARSE_CALLS" NUMBER(*,0) NOT NULL ENABLE, 
	"SORTS" NUMBER(*,0) NOT NULL ENABLE, 
	"KEPT_VERSIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"LOADS" NUMBER(*,0) NOT NULL ENABLE, 
	"ROWS_PROCESSED" NUMBER(*,0) NOT NULL ENABLE, 
	"INVALIDATIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"MODULE" VARCHAR2(48), 
	"ACTION" VARCHAR2(32), 
	"SQL_ID" VARCHAR2(13) NOT NULL ENABLE, 
	"DIRECT_WRITES" NUMBER, 
	"APPLICATION_WAIT_TIME" NUMBER, 
	"CONCURRENCY_WAIT_TIME" NUMBER, 
	"CLUSTER_WAIT_TIME" NUMBER, 
	"USER_IO_WAIT_TIME" NUMBER, 
	"PLSQL_EXEC_TIME" NUMBER, 
	"JAVA_EXEC_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"SQL_PROFILE" VARCHAR2(64), 
	"PROGRAM_NAME" VARCHAR2(128), 
	"PROGRAM_LINE#" NUMBER
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "YSSDATA";

