/* SQL statement 57 (ALTER;XXYSS_ADMIN;CONSTRAINT;PM_SEV_CK1;XXYSS_ADMIN;TABLE;PM_SYSTEM_EVENT;;;;;2) */
ALTER TABLE "XXYSS_ADMIN"."PM_SYSTEM_EVENT" ADD CONSTRAINT "PM_SEV_CK1" CHECK (
      db = upper(db) and
      run_id >= 1
      ) ENABLE;

