CREATE TABLE "XXYSS_ADMIN"."PM_CONFIG" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"CFG_NR" NUMBER(*,0) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(100) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(30) NOT NULL ENABLE
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "YSSDATA";

