CREATE TABLE "PM_SQL_ID" 
   (	"SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"COMMAND_TYPE" NUMBER NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"MODIFIED_BY" VARCHAR2(30) COLLATE "USING_NLS_COMP", 
	"MODIFICATION_DATE" DATE, 
	"SQL_TEXT" CLOB COLLATE "USING_NLS_COMP" NOT NULL ENABLE
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("SQL_TEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES );

