CREATE TABLE "PM_SQLAREA" 
   (	"DB" VARCHAR2(40) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"FIRST_LOAD_TIME" DATE NOT NULL ENABLE, 
	"HASH_VALUE" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(32) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARSING_USER_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"PARSING_SCHEMA_NAME" VARCHAR2(30) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"RUN_ID" NUMBER(*,0) NOT NULL ENABLE, 
	"EXECUTIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"BUFFER_GETS" NUMBER(*,0) NOT NULL ENABLE, 
	"DISK_READS" NUMBER(*,0) NOT NULL ENABLE, 
	"PARSE_CALLS" NUMBER(*,0) NOT NULL ENABLE, 
	"SORTS" NUMBER(*,0) NOT NULL ENABLE, 
	"KEPT_VERSIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"LOADS" NUMBER(*,0) NOT NULL ENABLE, 
	"ROWS_PROCESSED" NUMBER(*,0) NOT NULL ENABLE, 
	"INVALIDATIONS" NUMBER(*,0) NOT NULL ENABLE, 
	"MODULE" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"ACTION" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"SQL_ID" VARCHAR2(13) COLLATE "USING_NLS_COMP" NOT NULL ENABLE, 
	"DIRECT_WRITES" NUMBER, 
	"APPLICATION_WAIT_TIME" NUMBER, 
	"CONCURRENCY_WAIT_TIME" NUMBER, 
	"CLUSTER_WAIT_TIME" NUMBER, 
	"USER_IO_WAIT_TIME" NUMBER, 
	"PLSQL_EXEC_TIME" NUMBER, 
	"JAVA_EXEC_TIME" NUMBER, 
	"CPU_TIME" NUMBER, 
	"ELAPSED_TIME" NUMBER, 
	"SQL_PROFILE" VARCHAR2(64) COLLATE "USING_NLS_COMP", 
	"PROGRAM_NAME" VARCHAR2(128) COLLATE "USING_NLS_COMP", 
	"PROGRAM_LINE#" NUMBER
   )  DEFAULT COLLATION "USING_NLS_COMP"  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS";

