CREATE TABLE "XXYSS_ADMIN"."PM_SQL" 
   (	"DB" VARCHAR2(40) NOT NULL ENABLE, 
	"HASH_VALUE" NUMBER NOT NULL ENABLE, 
	"ADDRESS" VARCHAR2(32) NOT NULL ENABLE, 
	"SQL_ID" VARCHAR2(13) NOT NULL ENABLE
   )  
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "YSSDATA";

