ALTER TABLE "XXYSS_ADMIN"."PM_CONFIG" ADD CONSTRAINT "PM_CFG_CK1" CHECK (
      db = upper(db) and
      cfg_nr >= 1
      ) ENABLE;

ALTER TABLE "XXYSS_ADMIN"."PM_CONFIG" ADD CONSTRAINT "PM_CFG_PK" PRIMARY KEY ("DB", "CFG_NR") ENABLE;

