prompt @01.XXYSS_ADMIN.SEQUENCE.PM_RUN_SEQ.sql
@01.XXYSS_ADMIN.SEQUENCE.PM_RUN_SEQ.sql
prompt @01.XXYSS_ADMIN.SEQUENCE.PM_SQL_SEQ.sql
@01.XXYSS_ADMIN.SEQUENCE.PM_SQL_SEQ.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_CONFIG.sql
@06.XXYSS_ADMIN.TABLE.PM_CONFIG.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_RUN.sql
@06.XXYSS_ADMIN.TABLE.PM_RUN.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SESSION.sql
@06.XXYSS_ADMIN.TABLE.PM_SESSION.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SESSION_TMP.sql
@06.XXYSS_ADMIN.TABLE.PM_SESSION_TMP.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SQL.sql
@06.XXYSS_ADMIN.TABLE.PM_SQL.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SQLAREA.sql
@06.XXYSS_ADMIN.TABLE.PM_SQLAREA.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SQLAREA_TMP.sql
@06.XXYSS_ADMIN.TABLE.PM_SQLAREA_TMP.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SQL_CURRENT.sql
@06.XXYSS_ADMIN.TABLE.PM_SQL_CURRENT.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SQL_ID.sql
@06.XXYSS_ADMIN.TABLE.PM_SQL_ID.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SYSSTAT.sql
@06.XXYSS_ADMIN.TABLE.PM_SYSSTAT.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SYSSTAT_TMP.sql
@06.XXYSS_ADMIN.TABLE.PM_SYSSTAT_TMP.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SYSTEM_EVENT.sql
@06.XXYSS_ADMIN.TABLE.PM_SYSTEM_EVENT.sql
prompt @06.XXYSS_ADMIN.TABLE.PM_SYSTEM_EVENT_TMP.sql
@06.XXYSS_ADMIN.TABLE.PM_SYSTEM_EVENT_TMP.sql
prompt @R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM.sql
@R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM.sql
prompt @R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_CFG.sql
@R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_CFG.sql
prompt @R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_DPI.sql
@R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_DPI.sql
prompt @R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_MPI.sql
@R__09.XXYSS_ADMIN.PACKAGE_SPEC.PM_MPI.sql
prompt @R__10.XXYSS_ADMIN.VIEW.PM_VW_SQLAREA.sql
@R__10.XXYSS_ADMIN.VIEW.PM_VW_SQLAREA.sql
prompt @R__14.XXYSS_ADMIN.PACKAGE_BODY.PM.sql
@R__14.XXYSS_ADMIN.PACKAGE_BODY.PM.sql
prompt @R__14.XXYSS_ADMIN.PACKAGE_BODY.PM_CFG.sql
@R__14.XXYSS_ADMIN.PACKAGE_BODY.PM_CFG.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SQLAREA.sql
@16.XXYSS_ADMIN.INDEX.PM_SQLAREA.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SQLAREA_TMP.sql
@16.XXYSS_ADMIN.INDEX.PM_SQLAREA_TMP.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_CONFIG.sql
@16.XXYSS_ADMIN.INDEX.PM_CONFIG.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SQL_CURRENT.sql
@16.XXYSS_ADMIN.INDEX.PM_SQL_CURRENT.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_RUN.sql
@16.XXYSS_ADMIN.INDEX.PM_RUN.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SESSION.sql
@16.XXYSS_ADMIN.INDEX.PM_SESSION.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SYSTEM_EVENT_TMP.sql
@16.XXYSS_ADMIN.INDEX.PM_SYSTEM_EVENT_TMP.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SYSTEM_EVENT.sql
@16.XXYSS_ADMIN.INDEX.PM_SYSTEM_EVENT.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SQL_ID.sql
@16.XXYSS_ADMIN.INDEX.PM_SQL_ID.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SQL.sql
@16.XXYSS_ADMIN.INDEX.PM_SQL.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SESSION_TMP.sql
@16.XXYSS_ADMIN.INDEX.PM_SESSION_TMP.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SYSSTAT.sql
@16.XXYSS_ADMIN.INDEX.PM_SYSSTAT.sql
prompt @16.XXYSS_ADMIN.INDEX.PM_SYSSTAT_TMP.sql
@16.XXYSS_ADMIN.INDEX.PM_SYSSTAT_TMP.sql
prompt @R__18.XXYSS_ADMIN.OBJECT_GRANT.PM_CONFIG.sql
@R__18.XXYSS_ADMIN.OBJECT_GRANT.PM_CONFIG.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SQLAREA.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SQLAREA.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_CONFIG.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_CONFIG.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SQL_CURRENT.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SQL_CURRENT.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_RUN.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_RUN.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SESSION.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SESSION.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SYSTEM_EVENT_TMP.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SYSTEM_EVENT_TMP.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SYSTEM_EVENT.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SYSTEM_EVENT.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SQL_ID.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SQL_ID.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SQL.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SQL.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SESSION_TMP.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SESSION_TMP.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SYSSTAT.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SYSSTAT.sql
prompt @19.XXYSS_ADMIN.CONSTRAINT.PM_SYSSTAT_TMP.sql
@19.XXYSS_ADMIN.CONSTRAINT.PM_SYSSTAT_TMP.sql
prompt @20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SQLAREA.sql
@20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SQLAREA.sql
prompt @20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SESSION.sql
@20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SESSION.sql
prompt @20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SYSTEM_EVENT.sql
@20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SYSTEM_EVENT.sql
prompt @20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SQL.sql
@20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SQL.sql
prompt @20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SYSSTAT.sql
@20.XXYSS_ADMIN.REF_CONSTRAINT.PM_SYSSTAT.sql
